# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Under a Boddhi Tree
email: placeoftheway@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on functional programming, haskell, clojure, mathematics, buddhism and anything else that floats my boat.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rarebreed.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  rarebreed

# Build settings
markdown: kramdown
